apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.demos.fearofoblivion.com
spec:
  scope: Namespaced
  group: demos.fearofoblivion.com
  names:
    kind: Foo
    singular: foo
    plural: foos
  versions:
    - name: v1
      served: true
      storage: true
  preserveUnknownFields: true
  validation:
    openAPIV3Schema:
      type: object
      description: "A foo object"
      properties:
        spec:
          type: object
          properties:
            value1:
              type: string
            value2:
              type: string
              pattern: "^[a-zA-Z0-9]+"
            value3:
              type: integer
            value4:
              type: integer
              minimum: 1
              maximum: 10

---

apiVersion: "demos.fearofoblivion.com/v1"
kind: Foo
metadata:
  name: a-foo
spec:
  value1: "Hello World!"
  value2: "This is awesome!"
  value3: 42
  value4: 5